=== wmo-im/wis2box/tests/data/config/mapping_schema.json
{
    "$id": "csv2bufr.wis2.0.node.wis",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "inputDelayedDescriptorReplicationFactor": {
            "type": "array",
            "items": {"type": "integer"}
        },
        "unexpandedDescriptors": {
            "type": "array",
            "items": {"type": "integer"}
        },
        "header":{
            "type": "array",
            "items": {"$ref": "#/$defs/bufr_element"},
            "description": "Contents of header sections of BUFR message"
        },
        "data": {
            "type": "array",
            "items": {"$ref": "#/$defs/bufr_element"},
            "description": "mapping from CSV file (or metadata json file) to BUFR"
        }
    },
    "required" : ["inputDelayedDescriptorReplicationFactor","header","data"],
    "$defs":{
        "bufr_element": {
            "type": "object",
            "properties": {
                "eccodes_key": {
                    "type": "string",
                    "descripition": "eccodes key used to set the value in the BUFR data"
                },
                "value": {
                    "type": [
                        "boolean", "object", "array", "number", "string", "integer"
                    ],
                    "description": "fixed value to use for all data using this mapping"
                },
                "csv_column": {
                    "type": "string",
                    "description": "column from the CSV file to map to the BUFR element indicated by eccodes_key"
                },
                "jsonpath": {
                    "type": "string",
                    "description": "json path to the element in the JSON metadata file"
                },
                "valid_min": {
                    "type": "number",
                    "description": "Minimum valid value for parameter if set"
                },
                "valid_max": {
                    "type": "number",
                    "description": "Maximum value for for the parameter if set"
                },
                "scale": {
                    "type": "number",
                    "description": "Value used to scale the data by before encoding using the same conventions as in BUFR"
                },
                "offset": {
                    "type": "number",
                    "description": "Value added to the data before encoding to BUFR following the same conventions as BUFR"
                }
            },
            "required": ["eccodes_key"],
            "allOf": [
                {
                    "oneOf": [
                        {"required": ["value"]},
                        {"required": ["csv_column"]},
                        {"required": ["jsonpath"]}
                    ]
                },
                {
                    "dependentRequired": {"scale": ["offset"]}
                },
                {
                    "dependentRequired": {"offset": ["scale"]}
                }
            ]
        }
    }
}

=== wmo-im/wis2box/tests/data/config/malawi_synop_bufr.json
{
    "inputDelayedDescriptorReplicationFactor": [0,0],
    "unexpandedDescriptors": [301150,307080],
    "header":[
        {"eccodes_key": "edition", "value": 4},
        {"eccodes_key": "masterTableNumber", "value": 0},
        {"eccodes_key": "bufrHeaderCentre", "value": 0},
        {"eccodes_key": "bufrHeaderSubCentre", "value": 0},
        {"eccodes_key": "updateSequenceNumber", "value": 0},
        {"eccodes_key": "dataCategory", "value": 0},
        {"eccodes_key": "internationalDataSubCategory", "value": 6},
        {"eccodes_key": "masterTablesVersionNumber", "value": 36},
        {"eccodes_key": "numberOfSubsets", "value": 1},
        {"eccodes_key": "observedData", "value": 1},
        {"eccodes_key": "compressedData", "value": 0},
        {"eccodes_key": "typicalYear", "csv_column": "M_Year"},
        {"eccodes_key": "typicalMonth", "csv_column": "M_Month"},
        {"eccodes_key": "typicalDay", "csv_column": "M_DayOfMonth"},
        {"eccodes_key": "typicalHour", "csv_column": "M_HourOfDay"},
        {"eccodes_key": "typicalMinute", "csv_column": "M_Minutes"},
        {"eccodes_key": "unexpandedDescriptors", "value": [301150, 307080]}
    ],
    "data": [
        {"eccodes_key": "#1#wigosIdentifierSeries", "jsonpath": "$.wigosIds[0].wid_series"},
        {"eccodes_key": "#1#wigosIssuerOfIdentifier", "jsonpath": "$.wigosIds[0].wid_issuer"},
        {"eccodes_key": "#1#wigosIssueNumber", "jsonpath": "$.wigosIds[0].wid_issue_number"},
        {"eccodes_key": "#1#wigosLocalIdentifierCharacter", "jsonpath": "$.wigosIds[0].wid_local"},
        {"eccodes_key": "#1#stationOrSiteName", "jsonpath": "$.name"},
        {"eccodes_key": "#1#stationType", "csv_column": "WMO_Station_Type"},
        {"eccodes_key": "#1#year", "csv_column": "M_Year"},
        {"eccodes_key": "#1#month", "csv_column": "M_Month"},
        {"eccodes_key": "#1#day", "csv_column": "M_DayOfMonth"},
        {"eccodes_key": "#1#hour", "csv_column": "M_HourOfDay"},
        {"eccodes_key": "#1#minute", "csv_column": "M_Minutes"},
        {"eccodes_key": "#1#latitude", "jsonpath": "$.locations[0].latitude"},
        {"eccodes_key": "#1#longitude", "jsonpath": "$.locations[0].longitude"},
        {"eccodes_key": "#1#heightOfStationGroundAboveMeanSeaLevel", "jsonpath": "$.locations[0].elevation"},
        {"eccodes_key": "#1#heightOfBarometerAboveMeanSeaLevel", "csv_column": "BP_Elevation"},
        {"eccodes_key": "#1#nonCoordinatePressure", "csv_column": "BP"},
        {"eccodes_key": "#1#pressureReducedToMeanSeaLevel", "csv_column": "QNH"},
        {"eccodes_key": "#1#3HourPressureChange", "csv_column": "BP_Change"},
        {"eccodes_key": "#1#characteristicOfPressureTendency", "csv_column": "BP_Tendency"},
        {"eccodes_key": "#1#heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform", "csv_column": "Temp_H"},
        {"eccodes_key": "#1#airTemperature", "csv_column": "AirTempK"},
        {"eccodes_key": "#1#dewpointTemperature", "csv_column": "DewPointTempK"},
        {"eccodes_key": "#1#relativeHumidity", "csv_column": "RH"},
        {"eccodes_key": "#2#timePeriod", "csv_column": "Sun_hr"},
        {"eccodes_key": "#1#totalSunshine", "csv_column": "SunHrs"},
        {"eccodes_key": "#3#timePeriod", "csv_column": "Sun_hr24"},
        {"eccodes_key": "#2#totalSunshine", "csv_column": "SunHrs24"},
        {"eccodes_key": "#5#heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform", "csv_column": "Rain_H"},
        {"eccodes_key": "#4#timePeriod", "csv_column": "Rain_hr"},
        {"eccodes_key": "#1#totalPrecipitationOrTotalWaterEquivalent", "csv_column": "Rain_mm_Tot"},
        {"eccodes_key": "#6#heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform", "csv_column": "Temp_H"},
        {"eccodes_key": "#6#timePeriod", "csv_column": "Temp_hr24"},
        {"eccodes_key": "#7#timePeriod", "csv_column": "Temp24T"},
        {"eccodes_key": "#1#maximumTemperatureAtHeightAndOverPeriodSpecified", "csv_column": "AirTempMaxK"},
        {"eccodes_key": "#8#timePeriod", "csv_column": "Temp_hr24"},
        {"eccodes_key": "#9#timePeriod", "csv_column": "Temp24T"},
        {"eccodes_key": "#1#minimumTemperatureAtHeightAndOverPeriodSpecified", "csv_column": "AirTempMinK"},
        {"eccodes_key": "#7#heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform", "csv_column": "WSpeed_height"},
        {"eccodes_key": "#1#instrumentationForWindMeasurement", "csv_column": "Wind_Type"},
        {"eccodes_key": "#1#timeSignificance", "csv_column": "Wind_Sig"},
        {"eccodes_key": "#10#timePeriod", "csv_column": "Wind_T"},
        {"eccodes_key": "#1#windDirection", "csv_column": "WindDir"},
        {"eccodes_key": "#1#windSpeed", "csv_column": "WSpeed10M_Avg"},
        {"eccodes_key": "#2#timeSignificance", "csv_column": "WindG_Sig"},
        {"eccodes_key": "#1#maximumWindGustSpeed", "csv_column": "WindGust"},
        {"eccodes_key": "#14#timePeriod", "csv_column": "Solar_hr"},
        {"eccodes_key": "#1#globalSolarRadiationIntegratedOverPeriodSpecified", "csv_column": "SlrJ"},
        {"eccodes_key": "#15#timePeriod", "csv_column": "Solar_hr24"},
        {"eccodes_key": "#2#globalSolarRadiationIntegratedOverPeriodSpecified", "csv_column": "SlrJ24"}
    ]
}
